/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

 exports.seed = function (knex) {
  return knex("users")
    .del()
    .then(function () {
      return knex("users").insert([
        {
          city: "New York",
          email: "john.smith@example.com",
          first_name: "John",
          last_name: "Smith",
          password: "password123",
          confirm_password: "password123",
          phone_number: "(123) 456-7890",
          province: "NY",
          street_number: "10",
          username: "jsmith",
          country: "USA",
          img: "john.jpg",
          balance: "10000",
          last_opened: "2023-06-18",
          last_payment: "500",
          unique_id: "ABC123",
          last_payment_date: "2023-06-15",
          last_month_expense: "800"
        },
        {
          city: "Los Angeles",
          email: "emily.johnson@example.com",
          first_name: "Emily",
          last_name: "Johnson",
          password: "pass1234",
          confirm_password: "pass1234",
          phone_number: "(234) 567-8901",
          province: "CA",
          street_number: "22",
          username: "ejohnson",
          country: "USA",
          img: "emily.jpg",
          balance: "25000",
          last_opened: "2023-06-17",
          last_payment: "800",
          unique_id: "DEF456",
          last_payment_date: "2023-06-12",
          last_month_expense: "1200"
        },
        {
          city: "Toronto",
          email: "michael.williams@example.com",
          first_name: "Michael",
          last_name: "Williams",
          password: "hello123",
          confirm_password: "hello123",
          phone_number: "(345) 678-9012",
          province: "ON",
          street_number: "35",
          username: "mwilliams",
          country: "Canada",
          img: "michael.jpg",
          balance: "15000",
          last_opened: "2023-06-16",
          last_payment: "300",
          unique_id: "GHI789",
          last_payment_date: "2023-06-14",
          last_month_expense: "900"
        },
        {
          city: "Vancouver",
          email: "emma.jones@example.com",
          first_name: "Emma",
          last_name: "Jones",
          password: "welcome123",
          confirm_password: "welcome123",
          phone_number: "(456) 789-0123",
          province: "BC",
          street_number: "50",
          username: "ejones",
          country: "Canada",
          img: "emma.jpg",
          balance: "20000",
          last_opened: "2023-06-16",
          last_payment: "600",
          unique_id: "JKL012",
          last_payment_date: "2023-06-13",
          last_month_expense: "1100"
        },
        {
          city: "Chicago",
          email: "daniel.brown@example.com",
          first_name: "Daniel",
          last_name: "Brown",
          password: "12345678",
          confirm_password: "12345678",
          phone_number: "(567) 890-1234",
          province: "IL",
          street_number: "18",
          username: "dbrown",
          country: "USA",
          img: "daniel.jpg",
          balance: "18000",
          last_opened: "2023-06-15",
          last_payment: "400",
          unique_id: "MNO345",
          last_payment_date: "2023-06-11",
          last_month_expense: "950"
        },
        {
          city: "Houston",
          email: "olivia.davis@example.com",
          first_name: "Olivia",
          last_name: "Davis",
          password: "qwerty123",
          confirm_password: "qwerty123",
          phone_number: "(678) 901-2345",
          province: "TX",
          street_number: "75",
          username: "odavis",
          country: "USA",
          img: "olivia.jpg",
          balance: "22000",
          last_opened: "2023-06-14",
          last_payment: "700",
          unique_id: "PQR678",
          last_payment_date: "2023-06-10",
          last_month_expense: "1300"
        },
        {
          city: "Montreal",
          email: "matthew.miller@example.com",
          first_name: "Matthew",
          last_name: "Miller",
          password: "password456",
          confirm_password: "password456",
          phone_number: "(789) 012-3456",
          province: "QC",
          street_number: "28",
          username: "mmiller",
          country: "Canada",
          img: "matthew.jpg",
          balance: "19000",
          last_opened: "2023-06-13",
          last_payment: "450",
          unique_id: "STU901",
          last_payment_date: "2023-06-09",
          last_month_expense: "1000"
        },
        {
          city: "Miami",
          email: "sophia.wilson@example.com",
          first_name: "Sophia",
          last_name: "Wilson",
          password: "987654321",
          confirm_password: "987654321",
          phone_number: "(890) 123-4567",
          province: "FL",
          street_number: "42",
          username: "swilson",
          country: "USA",
          img: "sophia.jpg",
          balance: "28000",
          last_opened: "2023-06-12",
          last_payment: "900",
          unique_id: "VWX012",
          last_payment_date: "2023-06-08",
          last_month_expense: "1500"
        }
      ]);
    });
};
